# Generated by Django 5.2.4 on 2025-08-05 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='تمت المراجعة')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL, verbose_name='المستفسر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_received', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'استفسار',
                'verbose_name_plural': 'الاستفسارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
