# Generated by Django 5.2.4 on 2025-08-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reply_message',
            field=models.TextField(blank=True, null=True, verbose_name='رد صاحب العقار'),
        ),
    ]
