# Generated by Django 5.2.4 on 2025-08-04 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الميزة')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'مميزات',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/%d/', verbose_name='صورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور عقارات',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('commercial', 'محل/مكت'), ('chalet', 'شاليه'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العقار')),
                ('status', models.CharField(choices=[('for_sale', 'للبيع'), ('for_rent', 'للإيجار')], max_length=50, verbose_name='الحالة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('area', models.DecimalField(decimal_places=2, help_text='بالمتر المربع', max_digits=10, verbose_name='المساحة')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='عدد غرف النوم')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='عدد الحمامات')),
                ('location_address', models.CharField(max_length=255, verbose_name='العنوان بالتفصيل')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي/المنطقة')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
                ('features', models.ManyToManyField(blank=True, related_name='properties', to='properties.feature', verbose_name='المميزات')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'عقارات',
                'ordering': ['-published_date'],
            },
        ),
    ]
