# Generated by Django 5.2.4 on 2025-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_latitude_alter_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=17, null=True, verbose_name='خط الطول'),
        ),
    ]
