# Generated by Django 5.2.5 on 2025-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('land', 'أرض'), ('commercial', 'محل/مكتب'), ('chalet', 'شاليه'), ('other', 'أخرى')], max_length=50, verbose_name='نوع العقار'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=255, unique=True, verbose_name='الرابط المخصص'),
            preserve_default=False,
        ),
    ]
