# Generated by Django 5.2.5 on 2025-08-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_property_type_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
