# Generated by Django 5.2.5 on 2025-08-18 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='views_count',
        ),
        migrations.AddField(
            model_name='property',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_properties', to=settings.AUTH_USER_MODEL, verbose_name='شاهده المستخدمون'),
        ),
    ]
