# Generated by Django 5.2.5 on 2025-08-25 08:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_property_views_count_property_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='صورة'),
        ),
    ]
